### ISSUE TITLE
does this gem replace the info in chef docs?

### ISSUE THREAD

**Issue by bdangit** [chef/chef_backup#12]
Wondering if this needs to be up to date to reflect newer (and/or) better methods of backing up and restoring.

https://docs.chef.io/server_backup_restore.html

**Comment by ryancragun** [comment]
Hey @bdangit,

We definitely need to update the docs (and there is an open issue for that: https://github.com/chef/chef-web-docs/issues/472) but there are a few things in flux right now.  If you're using the latest version of the Chef Server you should be able to run the  `chef-server-ctl backup` and `chef-server-ctl restore` commands which in turn use this library to perform an _offline_ backup and restore of the Chef Server.  It requires rsync to be installed on the Chef Server host.

In the future this is going to be replaced with an online native backup support which is currently in development.  The Chef Server itself will have a backup and restore endpoints to allow remote backup/restore.
