### ISSUE TITLE
Restore on a chef aws marketplace instance throws error

### ISSUE THREAD

**Issue by nuoyan** [chef/chef_backup#13]
Stack trace: https://gist.github.com/nuoyan/af759711fac60e74be5a

Always reproducible. Seems that the private-chef cookbook is missing a condition on the 'chef-marketplace' as the topology name case.

**Comment by nuoyan** [comment]
So I added a condition to
/opt/opscode/embedded/cookbooks/private-chef/libraries/private_chef.rb
that when the topology is chef-marketplace, simply does nothing. That solved the problem.

```
    def generate_config_for_topology(topology, node_name)
      # TODO(ssd): This can be cleaned up once the "default"
      # topologies are also implemented using registered extensions
      case topology
      when "standalone","manual"
        PrivateChef[:api_fqdn] ||= node_name
        gen_api_fqdn
      when "ha", "tier"
        gen_redundant(node_name, topology)
      when "chef-marketplace"
        # does nothing
      else
```

However I can't find that cookbook anywhere on github, so I can't submit a pull request.

**Comment by ryancragun** [comment]
Sorry for the belated reply on this issue.  This should be resolved by https://github.com/chef/chef_backup/commit/bd29c56a0adb93c1443201088024b09f42b508a2.  You can track the upstream PR that bundles this fix in the Chef Server here https://github.com/chef/chef-server/pull/770
