### ISSUE TITLE
chef_backup Addon Reconfigure Incomplete

### ISSUE THREAD

**Issue by sean-horn** [chef/chef_backup#14]
Zendesk 7199

Tested on the following versions
Chef Server 12.3.1
Opscode Push Jobs 1.1.6
Manage 1.21
Reporting 1.5.3

As a customer, I would like any addons installed on my servers to continue working after a restore is complete.

Currently, the configuration and data for addons are restored, but their functionality is not.

If I have Reporting, Push jobs, and Manage installed on a Standalone chef server, I have to do the following to make the system fully functional after a `chef_backup restore ...` is run.

```
opscode-reporting-ctl reconfigure
opscode-push-jobs-server-ctl reconfigure
opscode-manage-ctl reconfigure
chef-server-ctl restart
opscode-manage-ctl restart
```

**Comment by ryancragun** [comment]
This should be resolved by https://github.com/chef/chef_backup/commit/bd29c56a0adb93c1443201088024b09f42b508a2.  You can track the upstream PR that bundles this fix here https://github.com/chef/chef-server/pull/770
