### ISSUE TITLE
Support Chef 11

### ISSUE THREAD

**Issue by pburkholder** [chef/chef_backup#4]
https://github.com/ryancragun/chef_backup/blob/master/lib/chef_backup/helpers.rb#L70 uses the chef-server-ctl command. Would we be able to backport this to Enterprise11 or OSC11?

**Comment by ryancragun** [comment]
This library is intended to be used in omnibus-ctl commands on the Chef Server so supporting EC11 wasn't really in the scope.  Two options: 1) a PR with backwards compat support and tests, 2) have the user create the symlink on their Chef Server.
